name: accessibility
description: An all-in-one solution to enhance your project with accessibility features.
version: 1.2.0
repository: https://github.com/RubenCesario/accessibility/tree/master
issue_tracker: https://github.com/RubenCesario/accessibility/issues
homepage: https://github.com/RubenCesario/accessibility
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics:
  - accessibility
  - a11y
  - utils
  - utility
  - theme

environment:
  sdk: ^3.3.0
  flutter: ">=1.17.0"

flutter:
  generate: true
  fonts:
    - family: Verdana
      fonts:
        - asset: lib/fonts/verdana.ttf
        - asset: lib/fonts/verdana-bold.ttf
          weight: 700
        - asset: lib/fonts/verdana-bold-italic.ttf
          weight: 700
          style: italic

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.1

screenshots:
  - description: The accessibility package logo.
    path: screenshots/logo.webp
  - description: The upper section of the accessibility settings panel.
    path: screenshots/settings_one.webp
  - description: The middle section of the accessibility settings panel.
    path: screenshots/settings_two.webp
  - description: The lower section of the accessibility settings panel.
    path: screenshots/settings_three.webp