name: web_deploy

on:
  push:
    branches:
      - master

jobs:
  flutter_web_deployment:
    name: Web deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/with_multiple_languages
    steps:
      - name: ğŸ¦ Checkout
        uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: ğŸ“¦ Installing dependencies
        run: flutter pub get

      - name: âš™ï¸ Building for the web
        run: flutter build web --csp

      - name: ğŸ“ Setting the git username
        run: git config user.name github-actions

      - name: ğŸ“§ Setting the git email
        run: git config user.email github-actions@github.com

      - name: ğŸ“¦ Adding web source
        run: git --work-tree build/web add --all

      - name: ğŸ“ Adding a commit message
        run: git commit -m "Automatic deployment by github-actions"

      - name: ğŸ“¤ Automatic web deployment
        run: git push origin HEAD:accessibility_web --force